version: '3.8'
services:
  log_router:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logrouter
    ports:
      - "8080:8080"
    env_file:
      - .env
    hostname: ${APP}
